[package]
name = "swiftness_stark"
description.workspace = true
edition.workspace = true
license-file.workspace = true
readme = "README.md"
repository.workspace = true
version.workspace = true

[features]
default = ["std"]
std = [
    "dep:thiserror",
    "starknet-core/std",
    "starknet-crypto/std",
    "swiftness_air/std",
    "swiftness_commitment/std",
    "swiftness_fri/std",
    "swiftness_pow/std",
]
test_fixtures = [
    "swiftness_air/test_fixtures",
    "swiftness_fri/test_fixtures",
    "swiftness_pow/test_fixtures",
]

[dependencies]
serde_with.workspace = true
serde.workspace = true
starknet-core.workspace = true
starknet-crypto.workspace = true
thiserror = { optional = true, workspace = true }
thiserror-no-std.workspace = true

swiftness_air.workspace = true
swiftness_commitment.workspace = true
swiftness_fri.workspace = true
swiftness_pow.workspace = true
swiftness_transcript.workspace = true

[dev-dependencies]
swiftness_air = { workspace = true, features = ["test_fixtures"] }
swiftness_fri = { workspace = true, features = ["test_fixtures"] }
swiftness_pow = { workspace = true, features = ["test_fixtures"] }